-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(PRICE*AMOUNT) AS 'TOTAL_SALES'
FROM FOOD_ORDER  FO
LEFT JOIN FOOD_PRODUCT FP ON FO.PRODUCT_ID = FP.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY FP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC , FP.PRODUCT_ID