-- 몇 시에 입양이 가장 활발하게 일어나는 지

WITH
T1 AS(
    SELECT 0 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 1 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 2 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 3 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 4 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 5 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 6 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 7 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 8 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 9 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 10 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 11 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 12 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 13 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 14 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 15 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 16 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 17 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 18 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 19 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 20 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 21 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 22 as HOUR, 0 as COUNT FROM dual
    UNION ALL
    SELECT 23 as HOUR, 0 as COUNT FROM dual
),
T2 AS(
    SELECT HOUR(DATETIME) as HOUR, COUNT(ANIMAL_ID) as COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
    ORDER BY HOUR
)
SELECT A.HOUR,
    CASE WHEN B.COUNT > 0 THEN B.COUNT
        ELSE A.COUNT END as COUNT
FROM T1 A
    LEFT JOIN T2 B ON A.HOUR = B.HOUR