WITH BOOK_AUTHOR AS (
    SELECT BOOK_ID,CATEGORY, B.AUTHOR_ID, AUTHOR_NAME, PRICE FROM BOOK B LEFT JOIN AUTHOR A
    ON B.AUTHOR_ID = A.AUTHOR_ID
)

SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES  FROM BOOK_AUTHOR BA LEFT JOIN 
(SELECT * FROM BOOK_SALES WHERE LEFT(SALES_DATE, 7) = '2022-01') BS
ON BA.BOOK_ID = BS.BOOK_ID
GROUP BY 2, 3
ORDER BY 1, 3 DESC