WITH USER_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE EXTRACT(YEAR FROM USER_INFO.JOINED) = '2021' 
),
SALES_USER AS (
    SELECT USER_2021.USER_ID, 
    YEAR(ONLINE_SALE.SALES_DATE) AS YEAR, 
    MONTH(ONLINE_SALE.SALES_DATE) AS MONTH, 
    ONLINE_SALE.SALES_AMOUNT
    FROM USER_2021
    INNER JOIN ONLINE_SALE
    ON USER_2021.USER_ID = ONLINE_SALE.USER_ID
)
SELECT YEAR, MONTH, COUNT(DISTINCT USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT USER_ID)/(SELECT COUNT(*) FROM USER_2021), 1) AS PURCHASED_RATIO
FROM SALES_USER
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH