
-- 코드를 입력하세요
SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS 'TOTAL_SALES'
FROM BOOK_SALES BS
LEFT JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
LEFT JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY B.AUTHOR_ID,  CATEGORY DESC