/*
- 재귀적인 문을 만들때는 "RECURSIVE" 단어 붙이기 -> 아니면 재귀라고 인식 못함.
- COALESCE는 항목에 default값 붙여줌.
*/

WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23
),
HOUREXIST AS (
    SELECT HOUR(ANIMAL_OUTS.DATETIME) AS "HOUR", COUNT(ANIMAL_ID) AS "COUNT"
    FROM ANIMAL_OUTS
    WHERE HOUR(ANIMAL_OUTS.DATETIME) >=0 AND HOUR(ANIMAL_OUTS.DATETIME) <= 23
    GROUP BY HOUR(ANIMAL_OUTS.DATETIME)
)
SELECT HOURS.HOUR, COALESCE(HOUREXIST.COUNT, 0)
FROM HOURS
LEFT JOIN HOUREXIST ON HOUREXIST.HOUR = HOURS.HOUR
ORDER BY HOURS.HOUR